config/routes.rb
Benchmark::Application.routes.draw do

  root :to => 'benches#index'

  resources :users
  resources :locations
  resources :benches
  resource :session

end

app/models/bench.rb
class Bench < ActiveRecord::Base
  attr_accessible :description, :image, :location_id#, :image_file_name, :image_content_type, :image

  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :details, :name

  has_many :benches
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :password_hash, :password_salt

  attr_accessor :password, :password_confirmation

  before_validation :encrypt_password

  validates :name, :presence => true
  validates :email, :presence => true
  validates :password_hash, :presence => true
  validates :password_salt, :presence => true
  validates :password, :confirmation => true

  def self.authenticate(email, password)
    user = find_by_email(email)

    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/benches_controller.rb
class BenchesController < ApplicationController


  def index
    @benches = Bench.all
  end

  def show
    @bench = Bench.find(params[:id])
  end

  def new
    @bench = Bench.new
    @locations = Location.all
  end

  def create
    @bench = Bench.new(params[:bench])
    if @bench.save
      redirect_to bench_path(@bench)
    else
      render :new
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(params[:location])
    if @location.save
      redirect_to locations_path
    else
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Take a seat you've been logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You've been benched!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/benches_helper.rb
module BenchesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/benches/index.html.erb
<h1>Benches</h1>
<% if flash[:notice] %>
  <h2><%= flash[:notice] %></h2>
<% end %>
<ul>
<% @benches.each do |bench| %>
  <li><%= link_to bench.location.try(:name), bench_path(bench) %></li>
<% end %>
</ul>

app/views/benches/new.html.erb
<h1>Create a Bench </h1>

<%= form_for @bench, :html => {:multipart => true} do |f| %>

  <%= f.select :location_id, @locations.map{|l| [l.name, l.id]} %>
  <div>
  <%= f.label :description %>
  <%= f.text_area :description %>
  </div>
    <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <%= f.submit :id => 'commit' %>
<% end %>

app/views/benches/show.html.erb
<h2><%= @bench.location_id %></h2>
<p><%= @bench.description %></p>
<%= image_tag @bench.image.url(:medium) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Benchmark</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
  <header>
    <h1 id="logo">Benchmark</h1>
    <% if session[:user_id] %>
    <nav>
      <ul>
      <li><%= link_to "Add a bench", new_bench_path %></li>
      <li><%= link_to "Add a location", new_location_path %></li>
      <li><%= link_to "Back to benches", benches_path %></li>
      <li><%= link_to "Log out", session_path, :confirm => 'Are you sure?', :method => :delete %></li>
    </ul>
  </nav>
    <% else %>
      <%= link_to "sign up", new_user_path %>
      <%= link_to "log in", new_session_path %>
    <% end %>
  </header>
  <%= yield %>
  <footer></footer>
</div>
</body>
</html>

app/views/locations/index.html.erb
<h1>Locations</h1>
<ul>
<% @locations.each do |location| %>
  <li><%= location.name %></li>
<% end %>
</ul>

app/views/locations/new.html.erb
<h1>Create a location </h1>

<%= form_for @location do |f| %>
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>
  <div>
  <%= f.label :details %>
  <%= f.text_area :details %>
  </div>

  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1>Create an Account </h1>

<%= form_for @user do |f| %>
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>
  <div>
  <%= f.label :email %>
  <%= f.text_field :email %>
  </div>
  <div>
  <%= f.label :password %>
  <%= f.password_field :password %>
  </div>
  <div>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit %>
<% end %>